### ISSUE TITLE
No sound after upgrade of LMS and Shairtunes - error in the log

### ISSUE THREAD

**Issue by larsfloe** [philippe44/LMS-ShairTunes2W#48]
Hello,

been using LMS and shairtunes for many years  on windows, I'm sorry for this:

after upgrading LMS the 8.4.0 and  shairtunes to 1.3.3. I see the follwing red line in the log:

Slim::Networking::IO::Select::__ANON__ (130) Error: Select task failed calling Plugins::ShairTunes2W::Plugin::handleSocketRead: Can't call method "pid" on an undefined value at C:\ProgramData\Squeezebox\Cache\InstalledPlugins/Plugins/ShairTunes2W/Plugin.pm line 869.
; fh=IO::Socket::INET=GLOB(0xdacbde4)

...I don't know what it is.... The plugin was always allowed in the firewall.
similar threads suggest unticking the "fill HTTP stream", but that has no effect on this error.
I've even tried a clean install on anohter PC, with the same result - any idea how to fix that error?

**Comment by larsfloe** [comment]
after dpwngrading back to 8-3-1 the Shairtunes works again..

**Comment by philippe44** [comment]
Interesting... I'll have a look at what's happening with 8.4.x on Win

**Comment by larsfloe** [comment]
thanks for reching out - your plug in is so great!

I downgraded to 8.3.1 and the issue is gone - I closed the ticket..

On 2023-11-12 07:42, philippe44 wrote:

> Interesting... I'll have a look at what's happening with 8.4.x on Win
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you modified the open/close 
> state.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/philippe44/LMS-ShairTunes2W/issues/48#issuecomment-1807020971
[2]
