### ISSUE TITLE
AirPlay targets are disappearing

### ISSUE THREAD

**Issue by vik-patel** [philippe44/LMS-ShairTunes2W#50]

**Comment by vik-patel** [comment]
I'm having an issue where AirPlay targets are disappearing ... running on a fresh install of Ubuntu with latest versions of LMS and ShairTunes2W ... after restarting lms I can see AirPlay targets and they work without issue ... after about 5-10mins they disappear ... any ideas?

**Comment by philippe44** [comment]
It's usually the same thing : some router in your network screws up with multicast and the LMS server is not on the same part of your network. Try to see if your router has something named IGMP snooping and then deactivate it

**Comment by vik-patel** [comment]
Nice! Fixed ... disabled igmp snooping on my netgear switch

**Comment by vik-patel** [comment]
Thx!
